# Generated by Django 4.0.2 on 2022-02-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='media', verbose_name='Image'),
        ),
    ]
