# Generated by Django 4.0.2 on 2022-02-17 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('SELLING', 'Selling'), ('BUYING', 'Buying')], max_length=255, verbose_name='type')),
                ('event', models.CharField(max_length=255, verbose_name='name of event')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('description', models.TextField(verbose_name='description')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
