# Generated by Django 4.0.2 on 2022-02-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Trondheim', max_length=255, verbose_name='location'),
            preserve_default=False,
        ),
    ]
