# Generated by Django 4.0.2 on 2022-03-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_available_post_traded_with'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['traded_with', '-id']},
        ),
    ]
